from PySubtitle.UnitTests.test_text import TestTextHelpers
from PySubtitle.UnitTests.test_Subtitles import TestSubtitles, SubtitleProcessorTests
from PySubtitle.UnitTests.test_Parse import TestParseDelayFromHeader, TestParseNames, TestParseValues
from PySubtitle.UnitTests.test_Substitutions import TestSubstitutions
from PySubtitle.UnitTests.test_Time import TestTimeHelpers
from PySubtitle.UnitTests.test_ChineseDinner import ChineseDinnerTests
from PySubtitle.UnitTests.test_Translator import SubtitleTranslatorTests
from PySubtitle.UnitTests.test_MergeSplitCommands import MergeSplitCommandsTests
from PySubtitle.UnitTests.test_MergeLinesCommand import MergeLinesCommandTest
from PySubtitle.UnitTests.test_DeleteLinesCommand import DeleteLinesCommandTest

